### PR TITLE
feat(cache): add Cache-Control middleware and update .env.example

### PR DESCRIPTION
**Pull request by abdelaziz-mahdy**
this works with vercel so its very nice to use

### CODE REVIEW

**Review by WBRK-dev — APPROVED** [review]
Didn't test, but code looks good.

**Comment by abdelaziz-mahdy** [comment]
> Didn't test, but code looks good.

Adding the headers makes the calls cached by vercel edge , which is awesome, the readme may add some info about it, but I may need some guidance on the format required

**Comment by ghoshRitesh12** [comment]
@abdelaziz-mahdy thank you so much for this amazing PR, there are a couple of changes, not logical but simple stylistic changes that I'd like you to make to maintain consistency is all 😄.

**Comment by abdelaziz-mahdy** [comment]
> @abdelaziz-mahdy thank you so much for this amazing PR, there are a couple of changes, not logical but simple stylistic changes that I'd like you to make to maintain consistency is all 😄.

all good from my side, i like this project so anything that will make it easier to maintain or help other people is on my table <3

**Comment by ghoshRitesh12** [comment]
> > @abdelaziz-mahdy thank you so much for this amazing PR, there are a couple of changes, not logical but simple stylistic changes that I'd like you to make to maintain consistency is all 😄.
> 
> all good from my side, i like this project so anything that will make it easier to maintain or help other people is on my table <3

@abdelaziz-mahdy thank you so much for understanding, also I've mentioned the required changes.

**Comment by ghoshRitesh12** [comment]
> @ghoshRitesh12 i am not sure, but did you not submit the review comments? i cant see it :(

Yeah I did

**Comment by abdelaziz-mahdy** [comment]
> > @ghoshRitesh12 i am not sure, but did you not submit the review comments? i cant see it :(
> 
> Yeah I did

can redo it, i cant see them, a screenshot will do for me, but github is showing me nothing currently

**Comment by ghoshRitesh12** [comment]
> > > @ghoshRitesh12 i am not sure, but did you not submit the review comments? i cant see it :(
> > 
> > Yeah I did
> 
> can you redo it, i cant see them, a screenshot will do for me, but github is showing me nothing currently

Here:

**Comment by abdelaziz-mahdy** [comment]
> > > > @ghoshRitesh12 i am not sure, but did you not submit the review comments? i cant see it :(
> > > 
> > > 
> > > Yeah I did
> > 
> > 
> > can you redo it, i cant see them, a screenshot will do for me, but github is showing me nothing currently
> 
> Here:
> 
> 

note its pending, which means it was not pushed to github, this is why its not showing to me :)

**Review by ghoshRitesh12 — CHANGES_REQUESTED** [review]
My bad, here they are

**Comment by abdelaziz-mahdy** [comment]
done.

**Pull request merged**
