### PR TITLE
Minor Enhancements

### PR DESCRIPTION
**Pull request by BySuspect**
### Things i added

- Minimum node version 18 added to Dev Dependencies (crashing on versions below v18).
- Prettier added for formatting and code style checks.
- Workflow added for checking code format in pull requests.

### CODE REVIEW

**Comment by BySuspect** [comment]
for better changelog [auto-changelog](https://github.com/cookpete/auto-changelog) is good

**Comment by ghoshRitesh12** [comment]
> for better changelog I recommend using [auto-changelog](https://github.com/cookpete/auto-changelog) and I can configure it if you like.

@BySuspect can you share any example or screenshot of how auto-changelog generated changelog?

**Comment by BySuspect** [comment]
> > for better changelog I recommend using [auto-changelog](https://github.com/cookpete/auto-changelog) and I can configure it if you like.
> 
> @BySuspect can you share any example or screenshot of how auto-changelog generated changelog?

@ghoshRitesh12  This screenshot is from my test repo I created a workflow that generates a changelog with every push for releases it generates a different changelog based on the specific version and is used for the release description.


2024 10 25v- %pn - 1104x823 - 300

2024 10 25v- %pn - 933x632 - 296


# template is this:
image

**Comment by BySuspect** [comment]
here is the sample from my project https://github.com/BySuspect/AutoPixAiCreditClaimer/blob/master/CHANGELOG.md

**Comment by ghoshRitesh12** [comment]
> here is the sample from my project https://github.com/BySuspect/AutoPixAiCreditClaimer/blob/master/CHANGELOG.md

I think I'll leave the changelogs as is.

**Review by ghoshRitesh12 — COMMENTED** [review]
Hey, I reviewed your changes and the change is only related to adding prettier config and CI lint check. Although it's a great change but the prettier config doesn't align with the project's config, hence I've pushed an update that introduces the same change, while limitting the number of files being affected in the change. 

Thank you, and I'm grateful for the time you spent trying to make this codebase better ❤.

**Pull request closed without merging**
